# Constants
EMAIL_FIELD_MAX_LENGTH = 254
INVALID_USERNAME = 'me'
FIRST_NAME_FIELD_MAX_LENGTH = 150
LAST_NAME_FIELD_MAX_LENGTH = 150
NAME_FIELD_MAX_LENGTH = 256
ROLE_MAX_LENGTH = 20
SLUG_FIELD_MAX_LENGTH = 50
USERNAME_FIELD_MAX_LENGTH = 150
MAX_STR_VALUE_LENGTH = 30
MIN_VALUE_SCORE = 1
MAX_VALUE_SCORE = 10

INVALID_CHAR = r'^[-a-zA-Z0-9_]+$'

USER_PROFILE_PATH = 'me'
